version: "2.2"

services:
  muzz:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    # environment:
      # CONFIG_FILE_PATH: /go/src/portCaptureServer/config/docker_compose_config.yaml
      # CONFIG_FILE_PATH: /app/.env
    ports:
    - 8080:8080

  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - muzzDB:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  muzzDB:
    external: false
